Repository Immortal17/CPP-Codes-DSA, pull requests merged in 2023-10, with the labels that each got.

#5 added leetcode solutions under random LC folder
  Random LC/firstandlast.cpp
  Random LC/leetcode744.cpp
Labels: good first issue, hacktoberfest-accepted

#7 Added Solutions to Leetcode Questions in C++
  Random LC Solns/NumbertoString.cpp
  Random LC Solns/firstandlast.cpp
  Random LC Solns/leetcode744.cpp
  Random LC Solns/lowerBound.cpp
  Random LC Solns/sorrtStrings.cpp
  Random LC Solns/sortZeroes.cpp
  Random LC Solns/tolowercase.cpp
Labels: hacktoberfest-accepted, Hacktoberfest

#8 added code
  Basic Patterns/1.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#11 Added Leetcode solutions to Arrays folder
  ARRAYS/Arrays/DNFAlgo.cpp
  ARRAYS/Arrays/IntersectionArr1.cpp
  ARRAYS/Arrays/KadaneAlgo.cpp
  ARRAYS/Arrays/KfrequentMap.cpp
  ARRAYS/Arrays/MajorityElement.cpp
  ARRAYS/Arrays/MissingNumber.cpp
  ARRAYS/Arrays/RearrangeBySign.cpp
  ARRAYS/Arrays/RemoveDuplicates.cpp
  ARRAYS/Arrays/RotateArray.cpp
  ARRAYS/Arrays/SumOfUnique.cpp
  ARRAYS/Arrays/TwoSum.cpp
  ARRAYS/Arrays/UniqueElement.cpp
  ARRAYS/Arrays/containsDuplicate.cpp
  ARRAYS/Arrays/duplicatelement.cpp
  ARRAYS/Arrays/longestSquence.cpp
  ARRAYS/Arrays/longestSubarray.cpp
  ARRAYS/Arrays/majortyElement2.cpp
  ARRAYS/Arrays/max1s.cpp
  ARRAYS/Arrays/moveZeroes.cpp
  ARRAYS/Arrays/panagram.cpp
  ARRAYS/Arrays/sortByParity.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#25 added codes
  Questions/characterhashing.cpp
  Questions/hashmaps.cpp
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#27 added code
  Questions/BSOnMatrix.cpp
  Questions/binarysearch.cpp
  Questions/binsearchstl.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#21 Added cpp code for Tower of Hanoi!
  Recursion/TowerOfHanoi.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#20 Remove_Duplicates.cpp
  ARRAYS/Remove_Duplicates.cpp
Labels: good first issue, hacktoberfest-accepted, hacktoberfest
